apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: default
data:
  # Base64-encode values (e.g., echo -n 'password' | base64)
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # Example